### PR TITLE
builder.dust: match v5.0.1 API

### PR DESCRIPTION
**Pull request by kalbasit**
updated the TS following https://htmlpreview.github.io/?https://raw.githubusercontent.com/dcodeIO/protobuf.js/master/docs/ProtoBuf.Builder.Message.html

### CODE REVIEW

**Comment by yellowiscool** [comment]
Thank you.

**Comment by tamird** [comment]
This needs to be reverted. `Buffer` is not defined in browser settings, so this change effectively breaks Proto2TypeScript for non-Node environments.

**Comment by kalbasit** [comment]
Not sure reverting is the right solution here as I only brought the library up to date. Should we source the definition of `Buffer` instead?

**Comment by tamird** [comment]
No, that would not be correct in non-Node environments.

Note that encodeNB **throws** in non-Node environments, so it is not expected to be usable from a browser.

**Comment by kalbasit** [comment]
@tamird true but again, this repo provides the TD of a protobuf, it does not assume NodeJS or Browser. So perhaps we could add a flag to enable node-only definitions?

@yellowiscool we should add node-only and browser-only tests to this repo?

**Comment by yellowiscool** [comment]
I don't know whether we should revert the commit. The "master" branch has never been very stable.

But we should definitely fix that. The flag to enable the node-only definitions is a good idea. The tests could also be improved, they were develop when I was the single user of the project, and they are far from perfect.

**Pull request merged**
